github:
  description: "Apache Flink Redis Streams Connector"
  homepage: https://flink.apache.org/
  labels:
    - flink
    - redis
    - streams
    - connector
    - big-data
    - java
    - real-time
    - datastream
    - table
    - sql
  enabled_merge_buttons:
    squash: true
    merge: false
    rebase: true
  autolink_jira: FLINK
  collaborators:
    - flinkbot
notifications:
  commits:      commits@flink.apache.org
  issues:       issues@flink.apache.org
  pullrequests: issues@flink.apache.org
  jobs:         builds@flink.apache.org
  jira_options: link label
